### PR TITLE
🚧 Add upsert functionality to batch_update

### PR DESCRIPTION
**Pull request by marks**
## Summary
Addresses 
> 'Upsert' option in the batch_update method

from  #208. Relevant Airtable API docs live at https://airtable.com/developers/web/api/update-multiple-records

## Example usage
Assumes a record already exists with `Unique ID` `aaa`
```python
inputRecords = [
    {'fields': {'Unique ID': 'aaa', 'First Name': 'A'}},
    {'fields': {'Unique ID': 'bbb', 'First Name': 'B'}}
]

upsert_result = table.batch_update(inputRecords, perform_upsert=dict(fieldsToMergeOn=['Unique ID']))
pprint(dict(upsert_result=upsert_result))
```
returns
```
{'upsert_result': {'created_record_ids': ['recIln1E0eUxq0S0i'],
                   'records': [{'createdTime': '2022-10-24T19:49:10.000Z',
                                'fields': {'First Name': 'aaa',
                                           'Name': 'aaa  (ID:aaa)',
                                           'Unique ID': 'aaa'},
                                'id': 'reckUKamPArJEfbwe'},
                               {'createdTime': '2022-12-04T22:12:25.000Z',
                                'fields': {'First Name': 'bbb',
                                           'Name': 'bbb  (ID:bbb)',
                                           'Unique ID': 'bbb'},
                                'id': 'recIln1E0eUxq0S0i'}],
                   'updated_record_ids': ['reckUKamPArJEfbwe']}}
```

### CODE REVIEW

**Comment by marks** [comment]
Hiya @gtalarico - first, thank you for this great library. This PR is very much a WIP but wanted to get your thoughts on it. A few things are top of mind for me:
1. [The introduction of `TypedDict`](https://github.com/gtalarico/pyairtable/pull/209/files#diff-8af5214420de7df4c6dd9f657201ccf78f6f8891391040d4880f5af26261bcffR19-R20)
2. Adding this functionality to the existing batch_update methods -- since there is a different return format, should this be a whole new function? (IMO, that would be a better end-user experience)
3. Or, to keep it simple, just return an array of records (this would mean not exposing information to the user which the API does return - IDs of created and updated records respectively)

**Comment by gtalarico** [comment]
Thanks Mark sorry I haven't had a chance to review this. On my to-do list

**Comment by MarekVigas** [comment]
Hey, can I help with this PR? What needs to be done to get this merged and released? I want to use it in my scripts.

**Comment by mesozoic** [comment]
Hi there! I'm trying to go through some older PRs in this repo and get them across the line. I'd love to see upsert functionality get merged in too, so I'm happy to help review this PR.

Personally, I think this makes most sense as its own method, since the mechanics are different, the return type is different (extra fields), and there is at least one required parameter (fields to merge) that isn't required for an update. Separating them out creates less opportunity to confuse the two behaviors or introduce bugs between the two. 

Perhaps something with a signature like this?

```python
class ApiAbstract:
    def _upsert(
        self,
        base_id: str,
        table_name: str,
        records: Sequence[Dict],
        merge_fields: Sequence[str],
        replace: bool = False,
        typecast: bool = False,
        return_fields_by_field_id: bool = False,
    ) -> List[Dict]:
        ...
```

I think we will also need to write a few tests for this endpoint, given how many different conditional behaviors they describe in the API documentation. 

For what it's worth, I wouldn't worry about introducing TypedDict right now. I'm working on a branch to implement strict typing across the entire library and it's moderately disruptive, so we're better off doing it all in one merge vs. trying to introduce it piecemeal with each new feature.

**Pull request closed without merging**
